config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'
  get 'contact/new'
  get 'contact/create'
  get 'contact_form/new'
  get 'contact_form/create'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show]


  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'



  get 'mail', to: 'pages#email'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'roi', to: 'pages#roi', as: 'roi'
  get 'angular-items', to: 'portfolios#angular'



get 'contact-me', to: 'messages#new', as: 'new_message'
post 'contact-me', to: 'messages#create', as: 'create_message'


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  

  root to: 'pages#home'



end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :phone, :email, :body
  validates :name, :phone, :email, :body, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new message_params

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to new_message_url, notice: "Message received, thanks!"
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :phone, :email, :body)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/new.html.erb
<!-- Global site tag (gtag.js) - Google Ads: 785838054 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-785838054"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-785838054');
</script>


<div class="container">
<div class="row justify-content-center">
  <div class="col-md-12">

<!-- Event snippet for Email conversion page
In your html page, add the snippet and call gtag_report_conversion when someone clicks on the chosen link or button. -->
<script>
function gtag_report_conversion(url) {
  var callback = function () {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  };
  gtag('event', 'conversion', {
      'send_to': 'AW-785838054/RdhBCOPv-4oBEObf2_YC',
      'event_callback': callback
  });
  return false;
}
</script>

  <div id="card-darkbg" class="card-darkbg">
  <h2>What do you need?</h2>

  <%= form_for @message, class: 'form', url: create_message_url do |f| %>

    <% if flash[:notice] -%>
      <div class = "alert alert-success"><%= flash[:notice] %></div>
    <% end %>

      <label>
        <%= f.text_field :name, placeholder: '' %>
        <div class="label-text">Name</div>
      </label>

      <label>
        <%= f.text_field :phone, placeholder: '' %>
        <div class="label-text">Phone</div>
      </label>

      <label>
        <%= f.email_field :email, placeholder: '' %>
        <div class="label-text">Email</div>
      </label>

      <label>
        <%= f.text_field :body, placeholder: ''  %>
        <div class="label-text">What you need</div>
      </label>

    <%= f.submit 'Send', class: 'btn btn-outline-info', :onclick => "gtag_report_conversion()" %>
  <% end %>

<br>
<div class="row justify-content-center">
    <button class="btn btn-outline-success">
      <a href="tel:9152419291" "call me">
        <p>
          <br>
            Press & hold to talk on the phone
          <br/>
            915-241-1648
          <br>
        </p>
      </a>
    </button>
</div>
<br>
<br>
        <p-s>
        <br>
        <br>
        We are located in El Paso, Texas, USA, we serve clients across the country.
        </p>
        <br>
        <br>
    <div class="row justify-content-center">
      <div class="col-md-6">

      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d216856.41317039504!2d-106.647923522168!3d31.869110151764946!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86e73f8bc5fe3b69%3A0xe39184e3ab9d0222!2sEl+Paso%2C+TX!5e0!3m2!1sen!2sus!4v1534647500057" width="400" height="420" frameborder="0" style="border:0" allowfullscreen></iframe>

      </div>
    </div>

  </div>


  </div>
</div>
</div>

<!--

<br>

        <form>
          <h2>What do you need?</h2>
          <label>
            <input type="text" required />
            <div class="label-text">name</div>
          </label>

          <label>
            <input type="text" required />
            <div class="label-text">phone #</div>
          </label>

            <label>
            <input type="text" required />
            <div class="label-text">What You Need</div>
          </label>

          <label>
            <input type="text" required />
            <div class="label-text">A short message</div>
          </label>

          <button>Submit</button>
</form>

-->