config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'
  get 'contact/new'
  get 'contact/create'
  get 'contact_form/new'
  get 'contact_form/create'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show]


  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'



  get 'mail', to: 'pages#email'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'roi', to: 'pages#roi', as: 'roi'
  get 'angular-items', to: 'portfolios#angular'



get 'contact-me', to: 'messages#new', as: 'new_message'
post 'contact-me', to: 'messages#create', as: 'create_message'


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  

  root to: 'pages#home'



end

app/models/portfolio.rb
class Portfolio < ApplicationRecord

  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                              reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image


  def self.angular
    where(subtitle: 'Angular')
  end

#begin drag and drop positioning for integer based position value



  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults
  
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')

  end







end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]

  layout "portfolio"

  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all


  def index
    @portfolio_items = Portfolio.all
#this lists and adjusts portfolio positions through the model definition of ascending order
  end

  def sort
  end
  

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'YOUR PORTFOLIO ITEM IS NOW LIVE' }
        format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
        format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
      respond_to do |format|
        if @portfolio_item.update(portfolio_params)
          format.html { redirect_to portfolios_path, notice: 'record was successfully updated.' }
          format.json { render :show, status: :ok, location: @portfolio_item }
        else
          format.html { render :edit }
          format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
        end
      end
    end

  def show

  end

  def destroy
    # perform the lookup
    # destroy the record
    @portfolio_item.destroy
    #redirect to the path and get out of there
    respond_to do |format|
    format.html { redirect_to portfolios_path, notice: 'record was successfully destroyed.' }
    end
  end


  private
    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body,
                                        technologies_attributes: [:name])
    end

    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end



end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <div class="form-group">
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name, class: 'form-control' %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
  <div class="col-md-4">
    
    <div class="card mb-4 box-shadow">
      <div class="row justify-content-center">
      <%= image_tag portfolio_item.thumb_image, style:"height: 100px; width:200px;" %>
      </div>
      <div class="card-body">

        <p class="card-text">
          <span>

          <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id), method: :get %>
            
          </span>
          <%= portfolio_item.subtitle %>
        </p>

        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <!--
            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
          -->
          </div>
          <small class="text-muted">9 mins</small>
        </div>
      </div>
    </div>

  </div>

app/views/portfolios/angular.html.erb
<h1>Angular portfolios items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin), method: :get %>

<% @angular_portfolio_items.each do |portfolio_item| %>

  <p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p> <%= portfolio_item.title %></p>
  <p> <%= portfolio_item.subtitle %></p>
  <p> <%= portfolio_item.body %></p>
  <p> <%= image_tag portfolio_item.thumb_image %> </p>

<%= link_to "Edit", edit_portfolio_path(portfolio_item.id), method: :get if logged_in?(:site_admin) %>

<td><%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></td>

<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">

          <%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

          <%= render partial: 'portfolio_item', collection: @portfolio_items %>

    </div>
  </div>
</div>

         <!-- <#%= render partial: 'portfolio_item', collection: @portfolio_items %> -->

app/views/portfolios/new.html.erb
<h1>create a new portfolio item</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<div class="container">

<div class="row justify-content-center">
    <div class="card ">
        <div class="col-md-7">
            <%= image_tag @portfolio_item.main_image, style:"height: 150px; width:250px;" %>
        </div>

        <div class="col-md-5">
                <h1> <%= @portfolio_item.title %> </h1>
                <hr>

            <em><%= @portfolio_item.subtitle %> </em>

            <p><%= @portfolio_item.body %> </p>

            <hr>

            <h3> Technology Used: </h3>
            <% @portfolio_item.technologies.each do |t| %>
            <p-small> <%= t.name %> </p-small>
            <% end %>
            <hr>
            <%= link_to "Instagram Clone", "https://ancient-inlet-27925.herokuapp.com/",
             class: 'btn btn-outline-info', method: :get %>
<br>
<br>
            <%= link_to "Real Estate Site Example", "https://ancient-inlet-27925.herokuapp.com/",
             class: 'btn btn-outline-info', method: :get %>
<br>
<br>
            <%= link_to "Application Dashboard Example", "https://ancient-inlet-27925.herokuapp.com/",
             class: 'btn btn-outline-info', method: :get %>
<br>
<br>
            <%= link_to "Listings Template", "https://ancient-inlet-27925.herokuapp.com/",
             class: 'btn btn-outline-info', method: :get %>
<br>
<br>


            <hr>
            <%= link_to 'back to all', portfolios_path, class: 'btn btn-outline-info', method: :get %>
        </div>

      </div>
</div>
</div>