config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'
  get 'contact/new'
  get 'contact/create'
  get 'contact_form/new'
  get 'contact_form/create'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show]


  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'



  get 'mail', to: 'pages#email'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'pricing', to: 'pages#pricing', as: 'pricing'
  get 'roi', to: 'pages#roi', as: 'roi'
  get 'angular-items', to: 'portfolios#angular'



get 'contact-me', to: 'messages#new', as: 'new_message'
post 'contact-me', to: 'messages#create', as: 'create_message'


  resources :blogs do
    member do
      get :toggle_status
    end
  end

  

  root to: 'pages#home'



end

app/views/shared/_application_footer.html.erb
    
<!-- Footer -->




<footer class="page-footer font-small mdb-color lighten-3 pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-lg-2 col-md-12 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="/assets/hubspot.png" class="img-fluid" alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>


      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="/assets/pipedrive.png" class="img-fluid" alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="/assets/uxdesign.png" class="img-fluid" alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-12 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="/assets/hubspot.png" class="img-fluid" alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="/assets/pipedrive.png" class="img-fluid" alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-2 col-md-6 mb-4">

        <!--Image-->
        <div class="view overlay z-depth-1-half">
          <img src="/assets/uxdesign.png" class="img-fluid" alt="">
          <a href="">
            <div class="mask rgba-white-light"></div>
          </a>
        </div>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">
      <%= copyright_generator %>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_application_header.html.erb
<nav class="navbar navbar-fixed-top navbar--color--primary navbar--size--xl" data-startColor="navbar--color--primary" data-startSize="navbar--size--xl" data-intoColor="navbar--color--ghost" data-intoSize="navbar--size--md">


      <div class="container justify-content-center">

        <a class="d" href="#">
          <div class="a" href="#"></div>
        </a>
        

        <div class="navbar-header">

          <%= link_to "Coffee Technologies", root_path, class: 'navbar-brand', method: :get %>
          <br/>
          <p-medium-green style="padding-left: 80px;">Creative Tech Solutions</p-medium-green>
          
        </div>

          <div class="navbar-right ml-auto">
            <% if flash[:notice] -%>
              <div class = "alert alert-success"><%= flash[:notice] %></div>
            <% end %>
          </div>

          <%# <div class="navbar-right ml-auto" style="padding-left: 80px;">
          <%= link_to "Packages", pricing_path, class: 'navbar-right btn btn-outline-success', method: :get %>
          </div> %>


          <%# <div class="navbar-right ml-auto">
          <%= link_to "Profitability Scaling", blogs_path, class: 'navbar-right btn btn-outline-success', method: :get %>
          </div> %>

          <div class="navbar-right ml-auto">
          <%= link_to "Contact", new_message_path, class: 'navbar-right btn btn-outline-success', method: :get %>
          </div>

          <div class="navbar-right ml-auto">
          </div>

          <div class="navbar-right ml-auto">
          <p-small-green><%= "*You are here: " + request.original_url %></p-small-green>
          </div>

      </div>

</nav>

  <div class="heroWrapper">
    <%# <div class="image-cropper">
      <div class="hero"> </div>
    </div> %>
  </div>

    <%= javascript_include_tag 'scroll_arrow.js' %>
    <%= javascript_include_tag 'header_nav.js' %>

app/views/shared/_application_nav.html.erb
<br>
<br>
<br>
<br>

<div class="container">



<div class="row">

<div class="col">

<header>



<ul>


      <%= link_to "Home", root_path, class: 'list-item', method: :get %>
<br>
      <%= link_to "About", about_me_path, class: 'list-item', method: :get %>
<br>
      <%= link_to "Contact", new_message_path, class: 'list-item', method: :get %>
<br>
      <%= link_to "Portfolio", portfolios_path, class: 'list-item', method: :get %>
<br>
      <%= link_to "Blog", blogs_path, class: 'list-item', method: :get %>
<br>
    


</ul>


</header>


<!--
</div> END COL 1 OF 3 





<div class="col">


      <h3>
        Hello from Step Technologies
      </h3>


</div>  END COL 2 OF 3




</div>  END ROW 
<br>

</div>  END CONTAINER 


-->

app/views/shared/_blog_footer.html.erb
        

        <footer class="blog-footer">

            <a href="#">Back to top</a>
          </p>
        <%= render "shared/nav", location: 'bottom' %>

        <%= source_helper("blog") %>
        </footer>


        

app/views/shared/_blog_masthead.html.erb
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Global site tag (gtag.js) - Google Ads: 785838054 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-785838054"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-785838054');
</script>


    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

app/views/shared/_blog_nav.html.erb
<!-- Start of nav -->
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">

        <%= link_to "Blog", blogs_path, class: 'nav-link active', method: :get  %>
        <%= link_to "Home", root_path, class: 'nav-link', method: :get %>
        <%= link_to "About", about_me_path, class: 'nav-link', method: :get  %>
        <%= link_to "Contact", new_message_path, class: 'nav-link', method: :get  %>
        <%= link_to "Portfolio", portfolios_path, class: 'nav-link', method: :get  %>
        <%= login_helper 'nav-link' %>
        
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
        <!-- start of sidebar -->
        <div class="col-sm-3 offset-sm-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h5>About</h5>
            <p><em>Coffee Technologies</em> strives not only to provide great marketing and tech solutions,
              but also the right information resources and research for people just finding
              the company. </p>
              <p> We plant our flag atop the never ending summit 
                  of the mountain that is technological progress, for your sake and ours. </p>
          </div>

          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled social-links">

              <li><a href="#"><%= fa_icon "github" %></li></a>

              <li><a href="#"><%= fa_icon "twitter" %></a></li>
              
            </ol>
          </div>
        </div>
        <!-- end of sidebar -->
        

app/views/shared/_nav.html.erb
  <div>
  <div style="padding-bottom: 4px"> 
    <%= link_to "Home", root_path, class: 'btn btn-outline-primary', method: :get %> </div>
  <div style="padding-bottom: 4px"> 
    <%= link_to "About", about_me_path, class: 'btn btn-outline-primary', method: :get %> </div>
  <div style="padding-bottom: 4px"> 
    <%= link_to "Contact", new_message_path, class: 'btn btn-outline-primary', method: :get %> </div>
  <div style="padding-bottom: 4px"> 
    <%= link_to "Portfolio", portfolios_path, class: 'btn btn-outline-primary', method: :get %> </div>
  <div style="padding-bottom: 4px"> 
    <%= link_to "Blog", blogs_path, class: 'btn btn-outline-primary', method: :get %> </div>
  </div>

app/views/shared/_portfolio_masthead.html.erb
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.

                <%= link_to "Create New Item", new_portfolio_path, class: "btn btn-outline-success", method: :get if logged_in?(:site_admin) %>

              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white"></h4>
              <ul class="list-unstyled">
                <li>
                <%= render "shared/nav", location: 'top' %></li>
                <span>
                <%= login_helper 'btn btn-outline-light' %></span>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong><%= @page_title %></strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>


    <main role="main">

       
        <div class="container">

        <h1 class="jumbotron">Recent Work Examples
        <p class="lead text-muted"> Built from scratch, just like Grandma's home-made apple pie </p>
        <p>
<%= tel_to 'Press & hold to call', '915-471-1866', class: 'navbar-right btn btn-outline-success' %>
<%= link_to "Contact", new_message_path, class: 'navbar-right btn btn-outline-success', method: :get %>


        
        </p>
        </h1>


        </div>
        

    </main>